var data = {"items":[
    {
        "y":-224,
        "name":"Dagger",
        "type":"Weapon",
        "description":"A short -mat- blade with a small hilt, stabs enemies",
        "gold":12,
        "damage":3
    },
    {
        "y":-192,
        "name":"Sword",
        "type":"Weapon",
        "description":"A sharp blade made of -mat-, cutting-edge medieval technology",
        "gold":20,
        "damage":5
    },
    {
        "y":-256,
        "name":"Hammer",
        "type":"Weapon",
        "description":"A heavy slab of -mat- with a handle",
        "gold":28,
        "damage":7
    },
    {
        "y":-96,
        "name":"Armour",
        "type":"Armour",
        "description":"An armour set made of -mat-, protects from damage",
        "gold":20,
        "defense":2
    }
],
"materials":[
    {
        "x":0,
        "name":"Bronze",
        "gold_mult":1,
        "damage_mult":1,
        "defense_mult":1,
    },
    {
        "x":-32,
        "name":"Iron",
        "gold_mult":2,
        "damage_mult":2,
        "defense_mult":2,
    },
    {
        "x":-32,
        "name":"Steel",
        "gold_mult":4,
        "damage_mult":4,
        "defense_mult":4,
    },
    {
        "x":-64,
        "name":"Cobalt",
        "gold_mult":8,
        "damage_mult":8,
        "defense_mult":8,
    },
    {
        "x":-96,
        "name":"Titanium",
        "gold_mult":16,
        "damage_mult":16,
        "defense_mult":16,
    },
    {
        "x":-128,
        "name":"Carbon",
        "gold_mult":32,
        "damage_mult":32,
        "defense_mult":32,
    },
    {
        "x":-160,
        "name":"Mystium",
        "gold_mult":32,
        "damage_mult":32,
        "defense_mult":32,
    },
    {
        "x":-192,
        "name":"Alienium",
        "gold_mult":64,
        "damage_mult":64,
        "defense_mult":64,
    },
    {
        "x":-224,
        "name":"Adamantine",
        "gold_mult":128,
        "damage_mult":128,
        "defense_mult":128,
    }
]}